qdrant/rust-client

src/channel_pool.rs

In this PR:
- Add test to catch lack of Send for get_channel
- Modifies get_channel to return a future that is Send
Motivation:
I am attempting to use qdrant/rust-client from a tonic-based grpc service's async_trait implementation e.g.:
```
pub struct MyServerStruct {
qdrant_client: qdrant_client::client::QdrantClient 
}
#[async_trait]
impl thing_api_server::ThingApi for MyServerStruct {
async fn list_things(
&self,
_request: Request<ListThingsRequest>,
) -> Result<Response<ListThingsResponse>, Status> {
// ...
let collections_response =  self.qdrant_client.list_collections().await; // <----
// ...
return Ok(Response::new(ListThingsResponse::default()));
}
}
```  
But I get a compile error hinting that something in the channel_pool is not `Send`
```
error: future cannot be sent between …
```

Modify get_channel to return a future that is Send

---

Cargo.toml
src/client.rs
src/lib.rs
tests/integration-tests.sh

This PR exposes the healthcheck endpoint to the client.

Expose healthcheck

---

Cargo.toml
proto/collections.proto
proto/collections_service.proto
proto/points.proto
proto/snapshots_service.proto
src/client.rs
src/lib.rs
src/qdrant.rs
tests/integration-tests.sh
tools/sync_proto.sh

Took the opportunity to add all missing alias related APIs as well.

v1.0.0 APIs

---

Cargo.toml
README.md
examples/search.rs
src/client.rs
src/lib.rs
src/qdrant.rs
src/serde.rs

This PR tackles #19 in a way that does not modify the build script.

Payload serde-json support

---

.github/workflows/lint.yml
src/lib.rs
tests/protos.rs

I removed all clippy and fmt issues, we can now verify it on CI.

check linting on CI

---

examples/search.rs
src/client.rs
src/lib.rs

QdrantClient::new is not async

---

src/lib.rs

While working on interfacing qdrant, I found that the API of the `Value` type is a bit weird, owing to the type being protobuf-compiled. This PR adds a few impls that makes working with such values a tad easier, notably `is_*` checks for the various types and `as_*` extractors as well as an `into_json` method if the serde feature is active.

Simplify `Value` API

---

src/lib.rs

This gives us at least some simple usage examples that people can use. The examples already show some weaknesses in our APIs; for example not all required types are in the prelude; some actions need multiple types to work; some builders or helper functions for common cases might improve developer experience.

add some crate docs

---

src/filters.rs

Noticed that the new `NestedCondition`s haven't had the same convenience treatment yet.
I've also added a recursive check for the unsupported `has_id` conditions in the filters; not sure how effective it will be, given that the initialiser is public, but if one uses only the convenience methods, it should work.
Because it is recursive, and thus potentially costly, it's only a `debug_assert` (although it's hard to imagine how massive the filters should become for it to be a performance toll). An alternative could be to impl `TryFrom` instead, but this wouldn't be semantically sound, as incorrect `NestedCondition`s shouldn't themselves be constructible in the first place, not `Condition`s on top of those.

impl `From<NestedCondition>` for `Condition` + validation + doc

---

src/filters.rs

Some improvements for capitalizing, punctuation, and adding auto-links

Improve descriptions in `filters.rs`

---

Cargo.toml

Bump v1.8.0

---

Cargo.toml
src/client.rs

Add support for GZip compression

---

src/error.rs
src/lib.rs

Replace macros [5]

---

examples/search.rs
src/qdrant.rs
tests/protos.rs
tests/protos_append/builder_ext.rs

SearchPoints builder

---

proto/collections.proto
proto/points.proto
src/grpc_ext.rs
src/lib.rs
src/manual_builder.rs
src/qdrant.rs
tests/builder_coverage.rs
tests/protos.rs
tests/protos_append/builder_ext.rs
tests/protos_append/grpc_macros.rs

Sync protos and add more Builder

---

src/qdrant.rs
tests/builder_coverage.rs
tests/protos.rs
tests/protos_append/builder_ext.rs

- Allows creating Builder for structs that are qualified with a path.
- Builder for DeletePoints

Delete points builder

---

src/grpc_ext.rs
src/qdrant.rs
tests/builder_coverage.rs
tests/protos.rs
tests/protos_append/builder_ext.rs

Finish builder

---

src/qdrant_client/points.rs

Implements all new functions for the points client.
Depends on #124

Api functions for points client

---

src/grpc_conversions/primitives.rs
src/manual_builder.rs
src/qdrant_client/errors.rs
src/qdrant_client/mod.rs
src/qdrant_client/points.rs
src/qdrant_client/snapshot.rs

Adds all snapshot client api calls
Depends on #125

Snapshot client API implementation

---

README.md

Add the following badge to our README:
[![docs.rs][docs-badge]][docs-url]
[docs-badge]: https://img.shields.io/docsrs/qdrant-client.svg
[docs-url]: https://docs.rs/qdrant-client
The backing page is still showing our current release. Once we publish v1.10 it'll update automatically.

Add docs.rs badge to README

---

src/lib.rs
src/qdrant.rs
tests/protos.rs

Mark deprecated gRPC types as deprecated

---

src/qdrant_client/query.rs

This updates the query API links.
At this time the link is still dead, but it'll be come available on release.
Rendered link: <https://deploy-preview-990--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/search/#query-api>

Update links for query API

---

tests/protos.rs

improve re-exports

---

Cargo.toml

Bump Rust client version to 1.10.2.

Bump version to 1.10.2

---

proto/points.proto
src/lib.rs
src/qdrant.rs

This PR does two things:
1. tackles the CI build issue https://github.com/qdrant/rust-client/actions/runs/10304982638/job/28524724939 by regenerating the proto files.
2. fix failing test due to long snapshot creation

Regen again

---

src/builder_ext.rs
src/grpc_conversions/query.rs
src/qdrant.rs
src/qdrant_client/query.rs
tests/builder_coverage.rs
tests/protos.rs
tests/snippet_tests/mod.rs
tests/snippet_tests/test_query_point_groups.rs
tests/snippet_tests/test_query_points.rs
tests/snippets/query_point_groups.rs
tests/snippets/query_points.rs

This PR exposes the new query groups API and adds example snippets.
I realized there were no snippets for query so I added some.

Add query groups API

---

proto/collections.proto
src/qdrant.rs

Tracking https://github.com/qdrant/qdrant/pull/4857

Regen for renumbering

---

src/qdrant_client/builders/query.rs

For the new random sampling feature

Add new_sample helper for Query

---

Cargo.toml

Update the Rust client to the latest Qdrant release.

Bump version to 1.12.0

---

src/qdrant.rs
src/qdrant_client/conversions/payloads.rs
tests/protos.rs

Adding missing implementations for:
- GeoIndexParams & builder
- BoolIndexParams

Add missing impls IndexParams

---

Cargo.toml
tests/integration-tests.sh

Follows the pattern of #209
Includes, primarily #218

Bump version to 1.14.0
