qdrant/rust-client

Cargo.toml
src/client.rs
src/prelude.rs

Add `Value` to the prelude, and stream the snapshot download to the file to reduce memory usage.

Reduce memory usage when downloading snapshot.

---

README.md

Fixes https://github.com/qdrant/rust-client/issues/21
This makes the example in the README up-to-date with the latest `qdrant-client` and `tokio` versions.

Fix example in README not compiling

---

Cargo.toml
README.md
examples/search.rs

Depends on https://github.com/qdrant/rust-client/pull/22
This extracts the README example to a binary example. This helps to catch compilation errors early as dependency APIs change.
This also improves the instructions for running the example, by defining the necessary `cargo add` command with dependencies.

Extract example to binary, improve instructions

---

Cargo.toml
src/client.rs
src/qdrant.rs

Needs extra care to handle the breaking change around max decoding size
- [release notes](https://github.com/hyperium/tonic/blob/master/CHANGELOG.md#v090-2023-03-31)
- [change](https://github.com/hyperium/tonic/pull/1335)

update to tonic 0.9

---

src/client.rs
src/lib.rs

When the `download_snapshots` isn't used, some compiler warnings were shown. This PR fixes that.
For example:
```rust
$ cargo check --no-default-features
warning: unused import: `bail`
--> src/client.rs:30:14
|
30 | use anyhow::{bail, Result};
|              ^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `std::path::PathBuf`
--> src/client.rs:35:5
|
35 | use std::path::PathBuf;
|     ^^^^^^^^^^^^^^^^^^
warning: `qdrant-client` (lib) generated 2 warnings (run `cargo fix --lib -p qdrant-client` to apply 2 suggestions)
Finished dev [unoptimized + debuginfo] target(s) in 7.50s
```

Fix compiler warnings without `download_snapshots` feature

---

Cargo.toml
src/client.rs
src/lib.rs

Adds a `serde` feature flag which enables the `serde` and `serde_json` dependencies and implementations (feature is enabled by default).

Add serde feature flag

---

README.md
src/client.rs

As discussed this morning, I added functionality to the client to split `upsert_point` calls with too many `points`. I randomly chose the split limit at 1024 points.
I also couldn't help myself and improved the client-connecting API to be more builder-like. See the README.md changes for the improvement. I can roll back this change if you think it's too much, but I personally don't think we'll have too high a maintainance cost for the nicer interface.

batch large upserts, improve client connect API

---

README.md
examples/search.rs
proto/collections.proto
src/client.rs
src/lib.rs
src/qdrant.rs

- Update Rust examples in documentation, add shard key selection

Update v1.7.0 - implementation

---

src/filters.rs
src/lib.rs

This PR addresses #85 which denotes that in order to use the full text search filter, a hacky workaround of inserting whitespace is required. This PR implements a dedicated function (`matches_text`) for initiating a full text-search, reflecting the python client's api.
Existing implementations of the full text search will continue to work as before.

Implementing dedicated function for full text search filtering

---

Cargo.toml

This PR adds missing metadata for the crates repositories.
Those tags are indexed and help people find what they need on `crates.io` and `lib.rs`
The possible categories can be found here https://crates.io/category_slugs
The keywords are free form.
e.g. https://crates.io/keywords/qdrant

Add crates.io metadata

---

Cargo.toml

Updates the dependencies that have newer versions available. 
Was there a reason to keep them pinned to their current version?

Bump outdated deps

---

src/client.rs
src/config.rs
src/lib.rs

Refactors some Config and related types/traits to config.rs

Refactor config and related types

---

src/client.rs
src/grpc_ext.rs
src/lib.rs

Puts existing From<> conversions and the `PointStruct` constructor into a separate file

Refactor impl blocks for grpc types [1]

---

.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/test.yml
tests/protos.rs

Switches from archived `actions-rs/toolchain@v1` to `dtolnay/rust-toolchain@stable` as toolchain and upgrade packages before installing dependencies with apt.
There is also a further test run  [here](https://github.com/qdrant/rust-client/actions/runs/9127168467) in a separate branch, using those changes.

Attempt to fix flaky test

---

src/grpc_conversions/extensions.rs
src/grpc_conversions/mod.rs
src/grpc_conversions/primitives.rs
src/lib.rs
src/manual_builder.rs
src/qdrant_client/collection.rs
src/qdrant_client/points.rs
src/qdrant_client/snapshot.rs

- Add more api calls to the `create_collection_and_do_the_search` test
- Migrated the tests in lib.rs to the new client
- Added a few more conversions into service types to make working with the new client even smoother
- Fixes ambiguous builder types `DeletePointsBuilder` caused by the `use manual_builder::*` in qdrant.rs
- Remove unused generic type parameter in `download_snapshot`

Migrate tests to new Qdrant client and fix various issues

---

examples/search.rs
src/builder_ext.rs
src/builder_types.rs
src/filters.rs
src/lib.rs
src/payload.rs
src/qdrant.rs
tests/protos.rs

This does a few things:
- expose `Payload` at the root level (maybe we don't want this, but it feels like a fine candidate to me)
- vendor `RecommendExample` and `Timestamp` in the `qdrant` module, that just makes more sense for endusers
- hide some more obsolete modules
- improve documentation
We're now left with:

Expose Payload at root, hide obsolete modules, vendor some types along in qdrant module

---

src/client/collection.rs
src/client/mod.rs
src/client/points.rs
src/client/snapshot.rs
src/lib.rs
src/qdrant_client/collection.rs
src/qdrant_client/config.rs
src/qdrant_client/error.rs
src/qdrant_client/mod.rs
src/qdrant_client/points.rs
src/qdrant_client/query.rs
src/qdrant_client/sharding_keys.rs
src/qdrant_client/snapshot.rs
tests/snippet_tests/test_batch_update.rs
tests/snippet_tests/test_create_shard_key.rs
tests/snippet_tests/test_delete_shard_key.rs
tests/snippet_tests/test_overwrite_payload.rs
tests/snippet_tests/test_scroll_points.rs
tests/snippet_tests/test_set_payload.rs
tests/snippet_tests/test_upsert_points.rs
tests/snippets/batch_update.rs
tests/snippets/create_shard_key.rs
tests/snippets/delete_shard_key.rs
tests/snippets/overwrite_payload.rs
tests/snippets/scroll_points.rs
tests/snippets/set_payload.rs
tests/snippets/upsert_points.rs

This PR adds makes various improvements around the crate documentation.
It is quite big, and I don't expect others to go through it line by line. It does not have code/logic changes. Examples are sourced from our test snippets.
As always, inspect these changes locally with: `cargo doc --no-deps --open`
It adds a basic connection example (and adds a Qdrant logo):
It adds basic operation documentation, a minimal example and links to our main documentation:
It hides deprecated modules:
Amongst other things.

Add documentation to operation/endpoint methods

---

src/lib.rs
src/payload.rs
src/qdrant_client/error.rs
src/serde.rs

This simplifies conversions between JSON and Payload in both directions. It adds a new error variant (`QdrantError::JsonToPayload`) and replaces the convoluted and isolated error type we had for this before.
It also replaces the `Payload::from_json_object` I had added with `Payload::try_from`.
I've added documentation for this to clearly show how to convert between the types:
The change does not introduce any new problems with the top 12 crates using `qdrant_client`. It therefore seems good enough in terms of backwards compatibility.

Simplify JSON to/from Payload conversions

---

.github/workflows/test.yml

We had constant CI errors due to inconsistent protobuf versions.
This updates our CI to use the same way of installing protobuf related dependencies as we do in the core repository here: https://github.com/qdrant/qdrant/blob/5c29cad76edc4fe33882d385c02633352666d67e/.github/workflows/rust.yml#L24-L27

Fix constant CI failures with protobuf installation, match core repo

---

src/qdrant.rs
src/qdrant_client/mod.rs
tests/protos.rs

Expose builders module

---

src/grpc_conversions/primitives.rs

Support
```rust
PointId::new("43cf51e2-8777-4f52-bc74-c2cbde0c8b04")
```
instead of just
```rust
PointId::new("43cf51e2-8777-4f52-bc74-c2cbde0c8b04".to_string())
```

Convert string slice into PointId

---

Cargo.toml

Release version 1.10.0 of the Rust client.
This is a huge release. We can elaborate on this in the change log when publishing the release tag.

Bump version to 1.10.0

---

src/qdrant_client/builders/mod.rs
src/qdrant_client/query.rs

We had the `VectorsConfigBuilder` in place before, but it was silently hidden.
We did expose it through the `vectors_config` module. However, our generated `qdrant.rs` has the exact same module name in it. Due to the name collision our builder types was silently ignored.
We now explicitly expose `VectorsConfigBuilder` and `SparseVectorsConfigBuilder` in `qdrant.rs` directly to prevent this problem:
- `qdrant_client::qdrant::VectorsConfigBuilder`
- `qdrant_client::qdrant::SparseVectorsConfigBuilder`

Expose (Sparse)VectorsConfigBuilder

---

src/channel_pool.rs

Related to:
- https://github.com/qdrant/rust-client/issues/170
- breaking changes in tonic 0.12 relese: https://github.com/hyperium/tonic/pull/1731

explicitly use nativ certificates

---

proto/collections.proto
proto/points.proto
src/qdrant.rs
src/qdrant_client/conversions/payloads.rs
tests/protos.rs

Sync Protos

---

Cargo.toml

Cut 1.11.0 release.
Next task is to create tag + GH release to publish crate.

Bump version to 1.11.0

---

src/qdrant_client/points.rs

Fixes <https://github.com/qdrant/rust-client/issues/174>.
Fix `upsert_points_chunked` doing an empty point update if the list of points is smaller than the specified chunk size.
This happened because we cleared the list of points before short cutting to a regular point update if the above condition was met.

Fix empty points update request when data is smaller than chunk size

---

src/qdrant_client/error.rs

This PR improves the error reporting when the server returns an error to return the full error message.
This is needed because it is currently very difficult for a user to understand why a request fails without looking into the server logs.
For instance when trying to create a malformed collection the client yields: 
```
Error in the response: Client specified an invalid argument
```
However the server logs say:
```
INFO qdrant::tonic::logging: gRPC /qdrant.Collections/Create failed with Client specified an invalid argument "Wrong input: `shard_number` cannot be 0"
```
With this PR the users will see the message as well.

Include actual server error message in reporting

---

Cargo.toml

A patch release (1.11.2) to include an important improvement to error reporting https://github.com/qdrant/rust-client/pull/185.

Bump version to 1.11.2

---

tests/protos.rs

This panic has been more annoying than helpful, so I suggest to demote it to just a warning message.

Demote protos generation panic to log message

---

Cargo.toml
src/channel_pool.rs

* Introduce a new dependency `rustc_version` to fetch Rust version.
* Extend user-agent header with info about client and rust versions, do it while creating a Channel 
2. [X] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [X] Have you checked your code using `cargo clippy --all --all-features` command?

Send client and rust version to server

---

src/filters.rs

Fix clippy errors that started to appear after latest rust update

Fix clippy

---

Cargo.toml
tests/integration-tests.sh

Update the Rust client to the latest Qdrant release, primarily including <https://github.com/qdrant/rust-client/pull/208>.
Follows the pattern of <https://github.com/qdrant/rust-client/pull/190>.

Bump version to 1.13.0

---

Cargo.toml

We had a lagging `dev` version of the client, which caused that `dev` bfb started showing client-server incompatibility messages.
This also makes it consistent with qdrant repo itself.

Bump dev version to `1.13.0-dev`

---

src/qdrant_client/error.rs

Additional information can be present in the response `metadata` so it makes sense to always display it in case of error to ease debugging.

Print metadata for error response display

---

Cargo.toml
src/grpc_conversions/extensions.rs

Fixes <https://github.com/qdrant/rust-client/issues/225>
Allows `PointId::from(uuid)` and `PointStruct::new(uuid, ...)` as requested [here](https://github.com/qdrant/rust-client/issues/225#issuecomment-2993211346).
Because we normally don't depend on `uuid` in our Rust crate, I've added it as optional dependency. Users can enable it as they please.

Construct point ID from UUID

---

Cargo.toml
tests/integration-tests.sh

Follows the pattern of <https://github.com/qdrant/rust-client/pull/219>
Primarily includes <https://github.com/qdrant/rust-client/pull/230>

Bump version to 1.15.0
